### ISSUE TITLE
zzz.com.ua

### ISSUE THREAD

**Issue by spirillen** [cbuijs/accomplist#13]
Hey Chris..

Noticed you have a bunch of `\.zzz\.com\.ua` domains on your list (https://0xacab.org/my-privacy-dns/matrix/-/issues/404025)

```bash
wget -O- https://raw.githubusercontent.com/cbuijs/accomplist/master/adult-themed/plain.black.domain.list | grep -iE '(^|\.)zzz\.com\.ua'
```

First of, most are dead, second, Why are they added? They all shows this page

![image](https://github.com/cbuijs/accomplist/assets/44526987/df234c21-6ac7-4905-b39a-da3ba2674f6c)

**Comment by cbuijs** [comment]
Hi @spirillen,

Not sure, the main source is "UT1 Porn" from here:
https://dsi.ut-capitole.fr/blacklists/index_en.php

There are only 29 domains, and they actually seem all to be active and are actually **NOT** dead (registered, resolvable and/or used)?

```
5infall.zzz.com.ua
alvaroshack.zzz.com.ua
ap0stal.zzz.com.ua
bancolomb-secure.zzz.com.ua
bx-server2384289.zzz.com.ua
dreamgaming.zzz.com.ua
dsvist.zzz.com.ua
fdg44.zzz.com.ua
hacker3456.zzz.com.ua
instahram.zzz.com.ua
kkkk.zzz.com.ua
laborjlps.zzz.com.ua
ld.zzz.com.ua
lnstagramhelp.zzz.com.ua
marlinoff.zzz.com.ua
mavro-reward.zzz.com.ua
nesk.zzz.com.ua
newworld.zzz.com.ua
pdfg.zzz.com.ua
ratnik123.zzz.com.ua
rememberu3.zzz.com.ua
sadhate.zzz.com.ua
strarwars.zzz.com.ua
vampastla.zzz.com.ua
vk-com-com.zzz.com.ua
vkbot.zzz.com.ua
vkfreestickers.zzz.com.ua
vkonakte.zzz.com.ua
webserver.zzz.com.ua
```
-Chris.

**Comment by spirillen** [comment]
Hey chris are able to get a screenshot of some contents ?

**Comment by cbuijs** [comment]
The SLD is used in a lot of malware/reputations lists. I'll keep it in for now.
