### ISSUE TITLE
whitelist beautyxt.app

### ISSUE THREAD

**Issue by soupslurpr** [cbuijs/accomplist#18]
Hi, I'm the developer of BeauTyXT which is a text and markdown file editor for Android. When googling for my app, I found this and it seems my domain beautyxt.app is in a blacklist at my-routedns/routedns.blocklist.domain.list. Is there a reason for this? Thanks.

**Comment by soupslurpr** [comment]
Oh OK that's good

**Comment by cbuijs** [comment]
No worries. I'll close this issue now, feel free to re-open if something pops up again.
