### ISSUE TITLE
manifest.googlevideo.com seems to be for YT Livestreams

### ISSUE THREAD

**Issue by yoshimo** [cbuijs/accomplist#19]
```manifest.googlevideo.com``` seems to break the YT LiveStream feature if blocked.

``` - https://raw.githubusercontent.com/cbuijs/accomplist/master/quantum/plain.black.domain.list``` is the file in question

**Comment by cbuijs** [comment]
It is coming from [Quantum Alpha](https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list) repo. I do not maintain it. Better tell them to remove it [here](https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/issues).

Note: I probably going to pull it from my repo as it has MANY false positives and A LOT of inactive domains.

**Comment by cbuijs** [comment]
Removed quantum from the repo. WIll refresh/update in the next 24h.
