### ISSUE TITLE
Whitelist request for empavion.app

### ISSUE THREAD

**Issue by eveetc** [cbuijs/accomplist#20]
Hey,

Just noticed empavion.app is on your blocklist (`accomplist` repo). This domain is part of our startup linked to [empavion.com](http://empavion.com/). Any idea why it's listed? Would appreciate if you could remove it.
Just for reference, you can read more about us for now on [mapuncover.com](https://mapuncover.com/) and about me on my portfolio site [eveschade.com](https://eveschade.com/).

Thanks for your assistance! 

https://github.com/cbuijs/accomplist/blob/master/my-routedns/routedns.blocklist.domain.list

**Comment by cbuijs** [comment]
Hey,

I searched the repo and it is not there (anymore). As I use many sources, my guess is that one of them unlisted it and as result cleaned up here too.

Let me know if this okay and we can close this.

**Comment by eveetc** [comment]
Hey Chris,

yes, the issue has been resolved. Thank you! :) 
I will close the issue.
