### ISSUE TITLE
keepassdx.com is a legit domain

### ISSUE THREAD

**Issue by najjara** [cbuijs/accomplist#21]
Hi!
The domain keepassdx.com for the open source app KeePassDX is listed on your typosquat list.
It's a legitimate and popular app, and the domain is their official website. You can check the Github repo here: https://github.com/Kunzisoft/KeePassDX

**Comment by cbuijs** [comment]
Hi Najjara,

Nice catch, thanks! It resembles "keypass" (the password manager) domains, that is why. I'll remove it. Will be updated within 24 hours.

Cheers,
-Chris.
