### ISSUE TITLE
Please whitelist simplex.chat

### ISSUE THREAD

**Issue by epoberezkin** [cbuijs/accomplist#22]
It seems that the whole TLD "chat" is in blacklist

https://simplex.chat

Thank you!

**Comment by cbuijs** [comment]
Hi,

Which blacklist do you use? The `.chat` TLD is considered extremely "dirty" and is included as a big hammer approach. You could simply whitelist 'simplex.chat' instead to stay safe perhaps?

-Chris.

**Comment by epoberezkin** [comment]
> The .chat TLD is considered extremely "dirty" and is included as a catch-all approach.

Out of curiosity, based on what?

> You could simply whitelist simplex.chat instead to stay safe perhaps?

Yes, this is what I am asking - if we can whitelist the specific domain in your list :)

**Comment by cbuijs** [comment]
>> The .chat TLD is considered extremely "dirty" and is included as a catch-all approach.
> Out of curiosity, based on what?

The number of sub-domains appear in a lot of different blocklists reoccurring is quite large. The reports and reputations of those domains is flagged on a daily basis, especially newly registered domains. Blocking `.chat` and allow listing of some that are okay is a better/secure approach.

>> You could simply whitelist simplex.chat instead to stay safe perhaps?
> Yes, this is what I am asking - if we can whitelist the specific domain in your list :)

No :-). You can just allowlist/override the one domain in your own system if you want is what I was suggesting :-).

I can add it to the allowlist (after checking), but I need to know which compilation is used. The TLD will still be blocked, but the allowlist could be used as an exception list (depending on you solution using the lists).

Lemme know what you think ;-).

**Comment by epoberezkin** [comment]
> Lemme know what you think ;-).

Will try to explain why I think you might be a questionable approach.

> Blocking .chat and allow listing of some that are okay is a better/secure approach.

That might be, but that amounts to a censorship of legitimate resources and of the whole TLDs simply because of the number of bad actors in that TLD. Inevitably, the new TLDs will attract a larger share of the total registration, and blocking the whole TLD is an anti-competitive practice, even if convenient.

> No :-). You can just allowlist/override the one domain in your own system if you want is what I was suggesting :-).

I am personally not affected. Our users of SimpleX Chat (and the visitors of the website) who use, for example, RethinkDNS are, and I cannot control their allowlists. If you think that blocking the whole TLD is a good practice, without a single complaint about particular domains (which I disagree with), then at the very least you could maintain the list of whitelisted resources alongside the list of potentially problematic TLDs, and communicate it to the users of the list (like RethinkDNS) that these lists should be used in parallel, and not transfer that responsibility to the end users of the affected services that use blocked TLDs, creating an anticompetitive environment.

This is very surprising that this is happening, to be honest, and it is totally undermines free speech and creates a very toxic environment where a large number of legitimite resources are shadow-banned (that is, these resources don't know they are banned) simply because of top TLD choice. Without a compensatory whitelist maintained by you it's even worse.

**Comment by cbuijs** [comment]
I am not blocking, ban or undermine anything, I just create lists that can be used by whoever and whatever want at their own risk and their own will.

I am not claiming these lists are faultless or perfect. I am just an aggregator like many other do. If it doesn't work for you, just don't use it? Use a commercial service/lists with guarantees and support? I am just doing hobby-work here.

**Comment by cbuijs** [comment]
After consideration I added `simplex.chat` to the [white-list repo](https://github.com/cbuijs/accomplist/tree/master/whitelist).

See this [list](https://github.com/cbuijs/accomplist/blob/master/whitelist/plain.white.domain.list) as example.

**Comment by epoberezkin** [comment]
> After consideration I added simplex.chat to the [white-list repo](https://github.com/cbuijs/accomplist/tree/master/whitelist).

Thank you, I really appreciate that.

> I am not blocking, banning, censoring, undermine or anti-compete anything, I just create lists that can be used by whoever and whatever want at their own risk and their own will.

Yep, I understand that. Hobbyists become authorities before they notice though :)

Thanks a lot, and thank you for your work.
