### ISSUE TITLE
Project Zero Blog 

### ISSUE THREAD

**Issue by yoshimo** [cbuijs/accomplist#23]
Google Project Zero and other blogs are hosted as CNAMEs of  blogspot.l.googleusercontent.com.
while the domain might host malicious stuff I think the collateral damage is too big.

**Comment by cbuijs** [comment]
Depends, you could/should allowlist that domain easier I think.

If I include all the "dirty" blogspot domains instead of a "catch all", the list will quadruple in size easily. I think it is a good trade-off.

**Comment by cbuijs** [comment]
@yoshimo can you provide some examples I can test with. I made some changes and everything seems to work as expected?

**Comment by yoshimo** [comment]
https://airlied.blogspot.com/2023/11/nouveau-gsp-firmware-support-current.html?m=1
http://googleprojectzero.blogspot.com/
https://richg42.blogspot.com/2015/11/lzham-custom-codec-plugin-for-7-zip.html
