### ISSUE TITLE
Domain listed for which reason?

### ISSUE THREAD

**Issue by woigl** [cbuijs/accomplist#25]
Good day,

I've found out that my domain `flowifier.app` is listed in the file `malicious-dom/plain.black.domain.list`.

Can you tell me why it is listed (is it a false positive?) and how I can remove it from your list?

Thanks in advance for your feedback.

Best Regards,
Stefan

**Comment by cbuijs** [comment]
Hi Stefan!

Sorry for late response, this is all on best-effort/private time ;-).

It is in there in one of the sources: [IOC2RPZ](https://ioc2rpz.net/).

In the `bforeai.ioc2rpz` category to be specific.

So it is listed at/by [BforeAI](https://bfore.ai/). They have a [support](https://bfore.ai/support/) page, where you can report issues/mistakes/false-positives.

Not sure why they list it, as they seem to be AI driven/powered, it might be a false-positive indeed. I have no connections with them or have any clue how they operate.

**Note:** When i go to [https://flowifier.app/](https://flowifier.app/), it is not up-n-running yet? Running on Azure?

-Chris

**Comment by walteste** [comment]
Hi Chris,

Thanks for your feedback.

It is not yet launched as the launch is planned for April 2024.

Cheers,
Stefan

**Comment by cbuijs** [comment]
No worries. Let me know how I can assist more, or close this issue/ticket.

**Comment by walteste** [comment]
Thanks, you can close the issue.
