### ISSUE TITLE
pdst.fm apex breaks podcast redirect chain

### ISSUE THREAD

**Issue by yoshimo** [cbuijs/accomplist#28]
`pdst.fm`
is used for the Thundercast episodes and media files can't be downloaded with this apex domain being blocked

`https://2.gum.fm/op3.dev/e/pdcn.co/e/pdst.fm/e/dts.podtrac.com/redirect.mp3/media.transistor.fm/da8c0690/2e4b4de8.mp3`

**Comment by cbuijs** [comment]
Which list are you using?

**Comment by yoshimo** [comment]
```
Exact match for pdst.fm found in:
 - https://raw.githubusercontent.com/cbuijs/accomplist/master/easylist/optimized.black.domain.list
```

**Comment by cbuijs** [comment]
It is blocked by `EasyPrivacy` source. I do not maintain it, I just consolidate.

See their [website](https://easylist.to/).
You can [report](https://forums.lanik.us/viewforum.php?f=64-report-incorrectly-removed-content) the error as well.
Or send them an [email](mailto:easylist@protonmail.com).

**Comment by yoshimo** [comment]
should you scrub away the limitations from ```||pdst.fm^$script,third-party``` in the first place?
