### ISSUE TITLE
PayPal broken

### ISSUE THREAD

**Issue by yoshimo** [cbuijs/accomplist#29]
https://github.com/badmojr/1Hosts/issues/533

**Comment by cbuijs** [comment]
Seems that [easylist](https://github.com/easylist/easylist) contains `c.paypal.com`. They also [allowlisted](https://github.com/search?q=repo%3Aeasylist%2Feasylist%20c.paypal.com&type=code) it.

I will add the allowlist lists to unbreak these kinds of mishaps.
