### ISSUE TITLE
What is this project

### ISSUE THREAD

**Issue by slankka** [cbuijs/accomplist#3]
Hi~, I found this interesting project when I googled 'dsm04pap003.storage.live.com' for proxy reason. 
Could you please give a brief explaination what is this project, and how to use it.

**Comment by Fusseldieb** [comment]
Same, searched for "firmwaresafe.com" since my cheap tablet pings this site looking for OTA updates for some reason, and stumbled upon this.

**Comment by cbuijs** [comment]
It is just a consolidation repo of block/allow-lists sources to be used for DNS filtering.
