### ISSUE TITLE
CHTBL.com is necessary for Podcasts

### ISSUE THREAD

**Issue by yoshimo** [cbuijs/accomplist#6]
As written in https://github.com/AdAway/adaway.github.io/issues/243 quite a few podcasts use the analytics capabilities of CHTLB and you don't get redirected to the proper episode file if this domain is blocked.

**Comment by cbuijs** [comment]
Hi @yoshimo - Could you point out which list(s) it is included in? I cannot find it?

**Comment by cbuijs** [comment]
I cannot find it? Is it spelled correctly? Can you provide a line number?

**Comment by yoshimo** [comment]
https://github.com/cbuijs/accomplist/blob/6cfb0d7f4ebd4e8d33ae26496a0ca36ea437867d/easylist/optimized.black.domain.list#L11139C1-L11139C1  11139

**Comment by cbuijs** [comment]
Looked into it, and there seems to be some privacy issues with that domain/site.

Source for the domain is [EasyPrivacy](https://easylist.to/easylist/easyprivacy.txt), I suggest you contact some of the authors mention here: https://easylist.to/pages/about.html

For now I don't take any action.
