### ISSUE TITLE
clients1.google.com on plain.black.domain.list

### ISSUE THREAD

**Issue by yoshimo** [cbuijs/accomplist#8]
This is an official subdomain and required for things like googles captive portal check on Android to work.
Is this intentionally on the list?

**Comment by cbuijs** [comment]
Hi @yoshimo,

I only found it in ["Quantum Alpha" list](https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/raw/master/For%20hosts%20file/The_Quantum_Ad-List.txt), I will try to ping them about it.

Good catch!

Just FYI: All other generated lists do NOT include it.
