### ISSUE TITLE
ghs.google.com breaks blogs

### ISSUE THREAD

**Issue by yoshimo** [cbuijs/accomplist#9]
Some people host their website at Google and this entry makes it impossible to reach them via CNAME to ghs.google.com

**Comment by cbuijs** [comment]
Hi @yoshimo,

I only found it in ["Quantum Alpha" list](https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/raw/master/For%20hosts%20file/The_Quantum_Ad-List.txt), I will try to ping them about it.

Good catch (again)!

Just FYI: All other generated lists do NOT include it.

P.S.: I might remove Quantum, as I get more false-positives on it.
